from prometheus_client import Counter, Histogram


REQUEST_COUNT = Counter(
    "http_requests_total",
    "Total number of HTTP requests.",
    ["method", "endpoint", "status"],
)


REQUEST_LATENCY = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency in seconds.",
    ["method", "endpoint"],
)


LLM_REQUEST_COUNT = Counter(
    "llm_requests_total",
    "Total number of LLM requests.",
    ["status"],
)


LLM_LATENCY = Histogram(
    "llm_request_duration_seconds",
    "LLM request latency in seconds.",
)


LLM_INPUT_TOKENS = Counter(
    "llm_input_tokens_total",
    "Total number of input tokens sent to the LLM.",
)


LLM_OUTPUT_TOKENS = Counter(
    "llm_output_tokens_total",
    "Total number of output tokens generated by the LLM.",
)
